### ISSUE TITLE
Text containing '&' is displayed incorrectly

### ISSUE THREAD

**Issue by dharber** [TextAnalysisTool/Releases#35]
It's possible this is intentional but it's certainly inconvenient.

If a line contains an ampersand, in at least some cases that ampersand is treated as a prefix to underline the following character, much like in Windows menu strings. This can be very confusing when analyzing log files that contain URL's with query parameters.

**Comment by DavidAnson** [comment]
Not intentional, sorry! I'm guessing this is a regression that was introduced with the change to work around a bug in the platform (GDI+) code that was responsible for the one exception that caused nearly every crash of the tool. With luck, the new API provides a flag to opt out of underlining. Thanks for reporting this!

**Comment by DavidAnson** [comment]
Fixed in the 2016-12-09 release, thank you!
